##
## This file allows non-volatile changes of the parameters for the
## acquisition software. In short, you can press the "Save parameters
## as standard", and the GUI overwrites details of the acquisition
## in the file. They will be ready to use when you open the software
## next time.
##

### ACQUISITION CONTROL SETTINGS
#Specify the acquisition filetype. A datatype which is compatible with the OpenWave software should be provided.
acq_filetype: 'hdf5'


### CAMERA SETTINGS
# use 0 for inbuilt webcam
cam_id: 0
#The mac webcam will start with these parameters
cam_frame_width: 1280
cam_fram_height: 720
cam_tExposure: 10.0 #ms
cam_nAccumulations: 1
cam_textFilename: ''
#The displacement and size of the sectioning of image B.
nImgX: 0
nImgY: 0
nImgN: 256
# Times between calculation iterations.
#   Increase if the CPU load gets excessive.
cam_histogram_timer: 300 #ms
cam_acquisition_timer: 50 #ms


### STAGE SETTINGS
stage_name: "demo"
# use com4 for NT or /dev/tty.usbmodem1421 for OSX
stage_port: "/dev/tty.usbmodem1421"
stage_baud: 9600
nStart: -52000
nStop: -54000
nStep: -10
